services:
  - type: web
    name: gst-it-portal
    runtime: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: RENDER
        value: "true"
    plan: standard
    healthCheckPath: /
